from __future__ import annotations

import streamlit as st


def render() -> None:
    st.title("Documentation")
    st.caption("Operational reference for architecture integration, result bundles, experiments, and plots.")

    st.markdown(
        '''
[Public Website](https://leolellisr.github.io/cogscore.github.io/)

[Playground Online](https://affix-decimeter-eradicate.ngrok-free.dev/)

'''
    )
    architecture_tab, results_tab, execution_tab, online_tab = st.tabs(
        ["Architecture bundles", "Result bundles", "Experiment execution", "Online deployment"]
    )
    with architecture_tab:
        st.markdown(
            """
### Required ZIP structure

```text
architecture_bundle.zip
├── manifest.yaml
├── Dockerfile
└── application source files
```

The service must listen on port `9000`, provide `GET /health`, and implement the benchmark-specific REST endpoints declared in `manifest.yaml`.
            """
        )
        st.code(
            """name: Example Architecture
version: "1.0"
author: Research Group
interface: rest
benchmarks:
  - sensory_buffer
  - attention_posner
  - motivation
  - learning""",
            language="yaml",
        )
    with results_tab:
        st.markdown(
            """
### Required ZIP structure

```text
result_bundle.zip
├── manifest.yaml
└── benchmark_out/
```

Learning bundles use `benchmark_out/AGENT/EXPERIMENT/...`. Sensing, attention, and motivation bundles contain the summary and per-trial CSV files generated by the corresponding benchmark runner.
            """
        )
    with execution_tab:
        st.markdown(
            """
1. Upload and validate an architecture.
2. Open **New experiment**.
3. Select the architecture and one of its declared benchmarks.
4. Choose a smoke-test, standard, or custom preset.
5. Review the complete request and launch the experiment.
6. Follow the run under **Experiment runs** and the worker operation under **Jobs**.
7. Inspect the generated figures under **Plots**.

The current remote runners validate the online architecture interface and workflow. Full equivalence with every local Java/CST experiment depends on the benchmark-specific bridge used by the runner.
            """
        )
    with online_tab:
        st.markdown(
            """
### Deployment controls

The dashboard supports optional password protection through:

```text
COGSCORE_DASHBOARD_USERNAME=researcher
COGSCORE_DASHBOARD_PASSWORD=change-me
```

Upload limits are controlled with `MAX_UPLOAD_BYTES`. Public deployments should additionally place the proxy behind institutional authentication, use per-user storage and execution quotas, and avoid exposing the raw VNC port directly.
            """
        )
