from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st

from .. import api_client
from ..common import resolve_data_path, render_exception


def _metadata(item: dict[str, Any]) -> dict[str, Any]:
    value = item.get("metadata")
    return value if isinstance(value, dict) else {}


def _benchmark_id(item: dict[str, Any]) -> str:
    benchmark = _metadata(item).get("benchmark", {})
    if isinstance(benchmark, dict) and benchmark.get("id"):
        return str(benchmark["id"])
    relative = str(item.get("relative_path", ""))
    return relative.split("/", 1)[0] if relative else "unknown"


def _benchmark_title(item: dict[str, Any]) -> str:
    benchmark = _metadata(item).get("benchmark", {})
    if isinstance(benchmark, dict) and benchmark.get("title"):
        return str(benchmark["title"])
    return _benchmark_id(item).replace("_", " ").title()


def _generation_id(item: dict[str, Any]) -> str:
    provenance = _metadata(item).get("provenance", {})
    if isinstance(provenance, dict) and provenance.get("generation_id"):
        return str(provenance["generation_id"])
    parts = str(item.get("relative_path", "")).split("/")
    return parts[2] if len(parts) >= 3 else parts[1] if len(parts) >= 2 else "legacy"


def _generation_label(item: dict[str, Any]) -> str:
    provenance = _metadata(item).get("provenance", {})
    generation = _generation_id(item)
    scope = provenance.get("scope", "") if isinstance(provenance, dict) else ""
    generated_at = provenance.get("generated_at", "") if isinstance(provenance, dict) else ""
    if generated_at:
        suffix = f" — {generated_at}"
    else:
        try:
            suffix = " — " + pd.to_datetime(item.get("modified_at"), unit="s").strftime("%Y-%m-%d %H:%M")
        except Exception:
            suffix = ""
    return f"{generation}{f' ({scope})' if scope else ''}{suffix}"


def _experiment_key(item: dict[str, Any]) -> str:
    experiment = _metadata(item).get("experiment", {})
    if isinstance(experiment, dict):
        return str(experiment.get("id") or experiment.get("title") or "unspecified")
    return "unspecified"


def _experiment_title(item: dict[str, Any]) -> str:
    experiment = _metadata(item).get("experiment", {})
    if isinstance(experiment, dict) and experiment.get("title"):
        return str(experiment["title"])
    return "Multiple or unspecified experimental conditions"


def _plot_title(item: dict[str, Any]) -> str:
    plot = _metadata(item).get("plot", {})
    if isinstance(plot, dict) and plot.get("title"):
        return str(plot["title"])
    return str(item.get("name", "Plot"))


def _render_rebuild_controls() -> None:
    st.divider()
    st.subheader("Generate a new comparison")
    st.caption("Rebuild creates a new generation without deleting previous plots. The newest valid result for each imported agent is included.")
    options = {
        "All benchmarks with results": "all",
        "Sensing": "sensory_buffer",
        "Attention": "attention_posner",
        "Motivation": "motivation",
        "Learning": "learning",
    }
    selected = st.selectbox("Benchmark to rebuild", list(options), key="replot_benchmark")
    action_col, refresh_col = st.columns(2)
    if action_col.button("Rebuild", type="primary", use_container_width=True):
        try:
            result = api_client.post_json("/plots/rebuild", {"benchmark": options[selected]})
            st.session_state["last_replot_result"] = result
            st.success(result.get("message", "Plot jobs created."))
        except Exception as exc:
            render_exception("Could not create plot jobs", exc)
    if refresh_col.button("Refresh plots", use_container_width=True):
        st.rerun()
    recent = st.session_state.get("last_replot_result", {}).get("jobs", [])
    if recent:
        st.dataframe(pd.DataFrame(recent), hide_index=True, use_container_width=True)


def _render_provenance(provenance: dict[str, Any]) -> None:
    fields = [
        ("Generated by", provenance.get("job_id") or provenance.get("generation_id")),
        ("Reference run", provenance.get("reference_run_id")),
        ("Scope", provenance.get("scope")),
        ("Generated at", provenance.get("generated_at")),
    ]
    for label, value in fields:
        if value:
            st.markdown(f"**{label}:** `{value}`")
    agents = provenance.get("selected_agents")
    if isinstance(agents, list) and agents:
        st.markdown("**Agents:** " + ", ".join(str(value) for value in agents))
    run_ids = provenance.get("selected_run_ids")
    if isinstance(run_ids, list) and run_ids:
        st.markdown("**Run IDs:**")
        for value in run_ids:
            st.code(str(value), language="text")
    with st.expander("Raw provenance"):
        st.json(provenance)


def render() -> None:
    st.title("Plots")
    st.caption("Explore generated results together with experiment, metric, processing, and provenance information.")
    try:
        items = api_client.get("/plots")
    except Exception as exc:
        render_exception("Could not load plot metadata", exc)
        return
    if not items:
        st.info("No plots were found. Import results and generate a comparison first.")
        _render_rebuild_controls()
        return

    image_extensions = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"}
    image_items = [item for item in items if str(item.get("extension", "")).lower() in image_extensions]
    html_items = [item for item in items if str(item.get("extension", "")).lower() == ".html"]
    all_items = [*image_items, *html_items]

    benchmark_ids = sorted({_benchmark_id(item) for item in all_items})
    examples = {value: next(item for item in all_items if _benchmark_id(item) == value) for value in benchmark_ids}
    requested_benchmark = st.query_params.get("benchmark", "")
    benchmark_index = benchmark_ids.index(requested_benchmark) if requested_benchmark in benchmark_ids else 0

    with st.container(border=True):
        selected_benchmark = st.selectbox("Benchmark", benchmark_ids, index=benchmark_index, format_func=lambda value: _benchmark_title(examples[value]))
        benchmark_images = [item for item in image_items if _benchmark_id(item) == selected_benchmark]
        benchmark_html = [item for item in html_items if _benchmark_id(item) == selected_benchmark]
        generation_examples: dict[str, dict[str, Any]] = {}
        for item in [*benchmark_images, *benchmark_html]:
            generation_examples.setdefault(_generation_id(item), item)
        generations = sorted(generation_examples, key=lambda value: float(generation_examples[value].get("modified_at", 0)), reverse=True)
        requested_generation = st.query_params.get("generation", "")
        generation_index = generations.index(requested_generation) if requested_generation in generations else 0
        selected_generation = st.selectbox("Generation", generations, index=generation_index, format_func=lambda value: _generation_label(generation_examples[value]))
        generation_images = [item for item in benchmark_images if _generation_id(item) == selected_generation]
        generation_html = [item for item in benchmark_html if _generation_id(item) == selected_generation]

        selected_experiment = ""
        selected_relative_path = ""
        selected_item: dict[str, Any] | None = None
        experiment_images: list[dict[str, Any]] = []
        if generation_images:
            experiment_examples: dict[str, dict[str, Any]] = {}
            for item in generation_images:
                experiment_examples.setdefault(_experiment_key(item), item)
            experiments = sorted(experiment_examples, key=lambda value: _experiment_title(experiment_examples[value]))
            requested_experiment = st.query_params.get("experiment", "")
            experiment_index = experiments.index(requested_experiment) if requested_experiment in experiments else 0
            selected_experiment = st.selectbox("Experiment", experiments, index=experiment_index, format_func=lambda value: _experiment_title(experiment_examples[value]))
            experiment_images = [item for item in generation_images if _experiment_key(item) == selected_experiment]
            plot_by_path = {str(item.get("relative_path")): item for item in experiment_images}
            paths = list(plot_by_path)
            requested_plot = st.query_params.get("plot", "")
            plot_index = paths.index(requested_plot) if requested_plot in paths else 0
            selected_relative_path = st.selectbox("Plot or measure", paths, index=plot_index, format_func=lambda value: _plot_title(plot_by_path[value]))
            selected_item = plot_by_path[selected_relative_path]

    st.query_params["page"] = "Plots"
    st.query_params["benchmark"] = selected_benchmark
    st.query_params["generation"] = selected_generation
    if selected_experiment:
        st.query_params["experiment"] = selected_experiment
    if selected_relative_path:
        st.query_params["plot"] = selected_relative_path

    if selected_item is not None:
        metadata = _metadata(selected_item)
        path = resolve_data_path(str(selected_item.get("path", "")))
        plot_column, info_column = st.columns([2, 1], gap="large")
        with plot_column:
            st.subheader(_plot_title(selected_item))
            if path.is_file():
                st.image(str(path), caption=str(selected_item.get("relative_path", "")), use_container_width=True)
                actions = st.columns(3)
                with path.open("rb") as stream:
                    actions[0].download_button("Download image", data=stream.read(), file_name=path.name, use_container_width=True)
                current_index = experiment_images.index(selected_item)
                if actions[1].button("← Previous", use_container_width=True, disabled=current_index == 0):
                    previous = experiment_images[current_index - 1]
                    st.query_params["plot"] = str(previous.get("relative_path", ""))
                    st.rerun()
                if actions[2].button("Next →", use_container_width=True, disabled=current_index >= len(experiment_images) - 1):
                    following = experiment_images[current_index + 1]
                    st.query_params["plot"] = str(following.get("relative_path", ""))
                    st.rerun()
                st.caption("Share this result using the current browser URL; the selected benchmark, generation, experiment, and plot are stored in the query parameters.")
            else:
                st.error(f"Plot file is not available at `{path}`.")

        with info_column:
            metric = metadata.get("metric", {}) if isinstance(metadata.get("metric"), dict) else {}
            quick = st.columns(2)
            quick[0].metric("Unit", metric.get("unit") or "Not specified")
            quick[1].metric("Preferred direction", metric.get("direction") or "Not specified")
            st.metric("Success threshold", metric.get("threshold") or "Not specified")
            tabs = st.tabs(["Experiment", "Measure", "Variables", "Interpretation", "Processing", "Provenance"])
            with tabs[0]:
                benchmark = metadata.get("benchmark", {}) if isinstance(metadata.get("benchmark"), dict) else {}
                experiment = metadata.get("experiment", {}) if isinstance(metadata.get("experiment"), dict) else {}
                if benchmark.get("description"):
                    st.markdown(str(benchmark["description"]))
                st.markdown(f"**{experiment.get('title', 'Experiment')}**")
                st.markdown(str(experiment.get("procedure") or "No procedure description is available."))
                st.markdown("**Expected behavior**")
                st.markdown(str(experiment.get("expected_behavior") or "No expected-behavior description is available."))
            with tabs[1]:
                st.markdown(f"**{metric.get('name', 'Measure')}**")
                st.markdown(str(metric.get("description") or "No measure description is available."))
                formula = str(metric.get("formula_latex") or "").strip()
                if formula:
                    st.latex(formula)
                if metric.get("range"):
                    st.markdown(f"**Range:** `{metric['range']}`")
            with tabs[2]:
                variables = metadata.get("variables", [])
                if isinstance(variables, list) and variables:
                    for variable in variables:
                        if isinstance(variable, dict):
                            st.markdown(f"**{variable.get('label', 'Variable')}** — {variable.get('description', '')}")
                else:
                    st.info("No variable description is available.")
            with tabs[3]:
                st.markdown(str(metadata.get("interpretation") or "No interpretation guidance is available."))
            with tabs[4]:
                processing = metadata.get("processing", {})
                if isinstance(processing, dict) and processing:
                    for key, value in processing.items():
                        st.markdown(f"**{str(key).replace('_', ' ').title()}:** `{value}`")
                    with st.expander("Raw processing metadata"):
                        st.json(processing)
                else:
                    st.info("No processing metadata is available.")
            with tabs[5]:
                provenance = metadata.get("provenance", {})
                if isinstance(provenance, dict) and provenance:
                    _render_provenance(provenance)
                else:
                    st.info("No provenance metadata is available.")

        with st.expander("Compare with another generation"):
            other_generations = [value for value in generations if value != selected_generation]
            if not other_generations:
                st.info("No other generation is available for this benchmark.")
            else:
                compare_generation = st.selectbox("Comparison generation", other_generations, format_func=lambda value: _generation_label(generation_examples[value]))
                candidates = [item for item in benchmark_images if _generation_id(item) == compare_generation and _experiment_key(item) == selected_experiment and _plot_title(item) == _plot_title(selected_item)]
                if candidates:
                    compare_path = resolve_data_path(str(candidates[0].get("path", "")))
                    compare_cols = st.columns(2)
                    compare_cols[0].image(str(path), caption=_generation_label(selected_item), use_container_width=True)
                    if compare_path.is_file():
                        compare_cols[1].image(str(compare_path), caption=_generation_label(candidates[0]), use_container_width=True)
                    else:
                        compare_cols[1].error("Comparison image is unavailable.")
                else:
                    st.info("The same measure was not found in the selected comparison generation.")

        if st.checkbox("Show all images in this experiment", value=False):
            columns = st.columns(2)
            for index, item in enumerate(experiment_images):
                gallery_path = resolve_data_path(str(item.get("path", "")))
                if gallery_path.is_file():
                    with columns[index % 2]:
                        st.markdown(f"**{_plot_title(item)}**")
                        st.image(str(gallery_path), use_container_width=True)
    elif not generation_html:
        st.info("No image plots were found for the selected generation.")

    if generation_html:
        import streamlit.components.v1 as components

        st.subheader("Interactive HTML plots")
        html_by_path = {str(item.get("relative_path")): item for item in generation_html}
        selected_html = st.selectbox("HTML plot", list(html_by_path), format_func=lambda value: _plot_title(html_by_path[value]))
        html_path = resolve_data_path(str(html_by_path[selected_html].get("path", "")))
        if html_path.is_file():
            components.html(html_path.read_text(encoding="utf-8", errors="replace"), height=800, scrolling=True)
        else:
            st.error("The selected HTML plot is unavailable.")

    _render_rebuild_controls()
