"""
Comparison plots for the Marta motivation benchmark agents.

Reads Java CSV files generated by MotivationTestRunner / MotivationEvaluationCodelet
and plots the five motivation experiments. It also adds two theoretical reference
agents by default:

    Substage1_Theoretic: reactive / non-motivational profile.
    Substage3_Theoretic: motivational / curiosity-driven profile.

Expected layout:
    results/output/AGENT_NAME/motivation_out/

Examples:
    python compare_motivation_agents_development.py --root results/output
    python compare_motivation_agents_development.py --root motivation_out --flat-root
    python compare_motivation_agents_development.py --root results/output --show
    python compare_motivation_agents_development.py --root results/output --theoretic-only
    python compare_motivation_agents_development.py --root results/output --no-theoretic
    python compare_motivation_agents_development.py --root results/output --experiment 5

Dependencies:
    pip install pandas matplotlib numpy
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional, Sequence

import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import hashlib

EXPERIMENT_NAMES = {
    1: "Exp 1: Persistence without stimulus",
    2: "Exp 2: Deprivation-satiation modulation",
    3: "Exp 3: Goal substitution / detour",
    4: "Exp 4: Latent learning",
    5: "Exp 5: Outcome devaluation",
    0: "Java step log",
}

FILE_PATTERNS = {
    "summary": ["*_exp*_summary_episode_*.csv", "*_summary_episode_*.csv"],
    "per_trial": ["*_exp*_per_trial_episode_*.csv", "*_per_trial_episode_*.csv"],
    "steps": ["*_java_steps_*.csv"],
}

TEXT_COLUMNS = {
    "agent",
    "agent_dir",
    "source_file",
    "architecture",
    "trial_id",
    "condition",
    "target_label",
    "target_role",
    "alternative_label",
    "control_label",
    "goal_label",
    "devalued_label",
    "first_raw_action",
    "first_action_category",
    "first_functional_action",
    "first_response_label",
    "first_look_label",
    "first_interaction_label",
    "first_interaction_role",
    "status",
    "phase",
}

METRIC_LABELS = {
    "mean_persistence_duration_cycles": "Persistence duration",
    "mean_persistence_selectivity": "Persistence selectivity",
    "persistence_duration_cycles": "Persistence duration",
    "persistence_selectivity": "Persistence selectivity",
    "resource_choice_probability": "Resource choice probability",
    "novelty_choice_probability": "Novelty choice probability",
    "control_choice_probability": "Control choice probability",
    "resource_modulation_index": "Resource modulation",
    "novelty_modulation_index": "Novelty modulation",
    "resource_choice": "Resource choice",
    "novelty_choice": "Novelty choice",
    "control_choice": "Control choice",
    "substitution_success_rate": "Substitution success",
    "substitution_success": "Substitution success",
    "mean_perseveration": "Perseveration",
    "perseveration": "Perseveration",
    "mean_detour_efficiency": "Detour efficiency",
    "detour_efficiency": "Detour efficiency",
    "mean_inspection_coverage": "Inspection coverage",
    "mean_manipulation_coverage": "Manipulation coverage",
    "inspection_coverage": "Inspection coverage",
    "manipulation_coverage": "Manipulation coverage",
    "first_attempt_accuracy_rate": "First-attempt accuracy",
    "first_attempt_accuracy": "First-attempt accuracy",
    "mean_first_interaction_efficiency": "First-interaction efficiency",
    "first_interaction_efficiency": "First-interaction efficiency",
    "latent_learning_gain_efficiency": "Latent-learning efficiency gain",
    "latent_learning_gain_latency": "Latent-learning latency gain",
    "mean_devaluation_sensitivity": "Devaluation sensitivity",
    "mean_response_suppression": "Response suppression",
    "devaluation_sensitivity": "Devaluation sensitivity",
    "response_suppression": "Response suppression",
    "behavioral_motivation_score": "Behavioral motivation score",
    "mean_motor_action_count": "Motor actions",
    "mean_virtual_action_count": "Virtual actions",
    "mean_attentional_action_count": "Attentional actions",
    "motor_action_count": "Motor actions",
    "virtual_action_count": "Virtual actions",
    "attentional_action_count": "Attentional actions",
    "raw_action_count": "Raw actions",
    "look_count": "Looks",
    "interaction_count": "Interactions",
    "omission_rate": "Omission rate",
    "trace_action_count": "Trace actions",
    "response_seq_to_simulator": "Response sequence",
}

REAL_AGENT_BASE_COLORS = [
    "tab:red",
    "tab:green",
    "tab:purple",
    "tab:brown",
    "tab:pink",
    "tab:orange",
]

THEORETIC_AGENT_COLORS = {
    "Substage1_Theoretic": "tab:gray",
    "Substage3_Theoretic": "tab:blue",
}

LINE_STYLES = ["-", "--", ":", "-."]
MARKERS = ["o", "s", "^", "D", "v", "P", "X", "*"]

DEFAULT_X_POINTS = 50
DEFAULT_SMOOTH_WINDOW = 7
DEFAULT_IMPUTE_LOOKBACK = 5

DEFAULT_BLEND_NOISE_PCT = 0.15
DEFAULT_BLEND_RANDOM_SEED = 12345

NON_BLEND_NUMERIC_COLUMNS = {
    "__source_row",
    "trial_index",
    "total_trials",
}


def stable_random_multiplier(
    *,
    seed: int,
    noise_pct: float,
    parts: list[object],
) -> float:
    """
    Deterministic random multiplier in [1 - noise_pct, 1 + noise_pct].

    It does not use Python's hash(), because hash() changes between runs.
    The same seed + same parts always generates the same multiplier.
    """
    if noise_pct <= 0.0:
        return 1.0

    key = "|".join(str(p) for p in parts)
    payload = f"{seed}|{key}".encode("utf-8")

    digest = hashlib.sha256(payload).digest()
    integer_value = int.from_bytes(digest[:8], byteorder="big", signed=False)

    unit = integer_value / float(2**64 - 1)
    low = 1.0 - noise_pct
    high = 1.0 + noise_pct

    return low + unit * (high - low)


def apply_metric_clip_if_needed(metric_name: str, values: pd.Series) -> pd.Series:
    clip = value_clip_range(metric_name)

    if clip is None:
        return values

    return values.clip(clip[0], clip[1])
# ---------------------------------------------------------------------
# Basic utilities
# ---------------------------------------------------------------------
def collapse_duplicate_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Pandas groupby fails when a dataframe has duplicate column names.
    This collapses duplicate columns by taking the first non-null value
    across columns with the same name.
    """
    if df.empty:
        return df

    out = df.copy()
    columns = pd.Index(out.columns)
    duplicate_names = columns[columns.duplicated()].unique()

    for name in duplicate_names:
        same_name = out.loc[:, out.columns == name]

        if same_name.shape[1] <= 1:
            continue

        combined = same_name.bfill(axis=1).iloc[:, 0]

        out = out.loc[:, out.columns != name]
        out[name] = combined

    return out


def metric_label(name: str) -> str:
    return METRIC_LABELS.get(str(name), str(name).replace("_", " ").title())


def experiment_label(exp_id) -> str:
    try:
        exp_id = int(exp_id)
    except Exception:
        return str(exp_id)
    return EXPERIMENT_NAMES.get(exp_id, f"Experiment {exp_id}")


def has_columns(df: pd.DataFrame, columns: Sequence[str]) -> bool:
    return not df.empty and all(c in df.columns for c in columns)


def ensure_output_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def save_plot(path: Path, show: bool) -> None:
    plt.tight_layout()
    plt.savefig(path, dpi=180, bbox_inches="tight")
    print(f"[SAVED] {path.resolve()}")
    if show:
        plt.show()
    plt.close()


def set_x_axis(ax, x_points: int) -> None:
    ax.set_xlim(1, x_points)
    if x_points <= 60:
        ticks = list(range(1, x_points + 1, 5))
        if x_points not in ticks:
            ticks.append(x_points)
        ax.set_xticks(sorted(set(ticks)))
    else:
        ax.set_xticks(np.linspace(1, x_points, 11, dtype=int))


def add_legend(ax, title: str) -> None:
    handles, _ = ax.get_legend_handles_labels()
    if handles:
        ax.legend(title=title, loc="best", fontsize=8)


def value_clip_range(metric: str) -> Optional[tuple[float, float]]:
    lower = metric.lower()
    if lower in {
        "mean_persistence_selectivity",
        "persistence_selectivity",
        "resource_choice_probability",
        "novelty_choice_probability",
        "control_choice_probability",
        "resource_modulation_index",
        "novelty_modulation_index",
        "resource_choice",
        "novelty_choice",
        "control_choice",
        "substitution_success_rate",
        "substitution_success",
        "mean_perseveration",
        "perseveration",
        "mean_detour_efficiency",
        "detour_efficiency",
        "mean_inspection_coverage",
        "mean_manipulation_coverage",
        "inspection_coverage",
        "manipulation_coverage",
        "first_attempt_accuracy_rate",
        "first_attempt_accuracy",
        "mean_first_interaction_efficiency",
        "first_interaction_efficiency",
        "latent_learning_gain_efficiency",
        "mean_devaluation_sensitivity",
        "mean_response_suppression",
        "devaluation_sensitivity",
        "response_suppression",
        "behavioral_motivation_score",
        "omission_rate",
    }:
        return 0.0, 1.0
    return None


def build_agent_colors(data: dict[str, pd.DataFrame]) -> dict[str, str]:
    agents: set[str] = set()
    for df in data.values():
        if not df.empty and "agent" in df.columns:
            agents.update(df["agent"].dropna().astype(str).tolist())

    colors: dict[str, str] = {}
    for agent, color in THEORETIC_AGENT_COLORS.items():
        if agent in agents:
            colors[agent] = color

    real_agents = sorted(agent for agent in agents if agent not in THEORETIC_AGENT_COLORS)
    for i, agent in enumerate(real_agents):
        colors[agent] = REAL_AGENT_BASE_COLORS[i % len(REAL_AGENT_BASE_COLORS)]
    return colors


def vary_color(base_color: str, variant_index: int) -> tuple[float, float, float]:
    rgb = np.array(mcolors.to_rgb(base_color), dtype=float)
    factors = [1.00, 1.25, 0.75, 1.45, 0.55, 1.65, 0.40]
    factor = factors[variant_index % len(factors)]
    if factor >= 1.0:
        amount = min(factor - 1.0, 0.80)
        out = rgb + (1.0 - rgb) * amount
    else:
        out = rgb * factor
    return tuple(np.clip(out, 0.0, 1.0))


# ---------------------------------------------------------------------
# Loading and cleaning
# ---------------------------------------------------------------------


def discover_agents(root: Path, benchmark_dir_name: str, only_agents: Optional[list[str]], flat_root: bool) -> list[tuple[str, Path]]:
    if flat_root:
        agent_name = root.name if root.name else "agent"
        return [(agent_name, root)] if root.exists() else []

    if not root.exists():
        return []

    agents: list[tuple[str, Path]] = []
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        if only_agents and child.name not in only_agents:
            continue
        benchmark_dir = child / benchmark_dir_name
        if benchmark_dir.exists() and benchmark_dir.is_dir():
            agents.append((child.name, benchmark_dir))
    return agents


def read_agent_csvs(agent_name: str, benchmark_dir: Path, key: str) -> pd.DataFrame:
    paths: list[Path] = []
    for pattern in FILE_PATTERNS[key]:
        paths.extend(sorted(benchmark_dir.rglob(pattern)))
    paths = sorted(set(paths))

    frames: list[pd.DataFrame] = []
    for path in paths:
        try:
            df = pd.read_csv(path)
            df["agent"] = agent_name
            df["agent_dir"] = str(benchmark_dir)
            df["source_file"] = str(path)
            df["__source_row"] = range(len(df))
            frames.append(df)
        except Exception as exc:
            print(f"[WARN] Could not read {path}: {exc}", file=sys.stderr)

    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True, sort=False)


def load_all_agents(root: Path, benchmark_dir_name: str, only_agents: Optional[list[str]], flat_root: bool) -> dict[str, pd.DataFrame]:
    agents = discover_agents(root, benchmark_dir_name, only_agents, flat_root)

    print("[INFO] Agents discovered:")
    for agent_name, benchmark_dir in agents:
        print(f"  {agent_name}: {benchmark_dir}")

    if not agents:
        print(f"[WARN] No agents found under {root}", file=sys.stderr)

    loaded: dict[str, list[pd.DataFrame]] = {key: [] for key in FILE_PATTERNS}
    for agent_name, benchmark_dir in agents:
        for key in FILE_PATTERNS:
            df = read_agent_csvs(agent_name, benchmark_dir, key)
            if not df.empty:
                loaded[key].append(df)

    combined = {
        key: pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()
        for key, frames in loaded.items()
    }

    print("\n[INFO] Loaded rows:")
    for key, df in combined.items():
        print(f"  {key:10s}: {len(df)}")
    return combined


def normalize_common_columns(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df

    out = df.copy()
    out.columns = [str(c).strip() for c in out.columns]

    if "episode" not in out.columns and "epoch" in out.columns:
        out["episode"] = out["epoch"]
    if "episode" not in out.columns:
        out["episode"] = 0

    if "motivation_experiment_id" not in out.columns:
        for candidate in ["experiment_id", "active_motivation_experiment_id", "exp_id", "motivation_exp_id"]:
            if candidate in out.columns:
                out["motivation_experiment_id"] = out[candidate]
                break
    if "motivation_experiment_id" not in out.columns:
        out["motivation_experiment_id"] = np.nan

    if "trial_index" not in out.columns and "trial" in out.columns:
        out["trial_index"] = out["trial"]

    return out


def clean_frame(df: pd.DataFrame, episode: Optional[int], experiment: Optional[int]) -> pd.DataFrame:
    if df.empty:
        return df

    out = normalize_common_columns(df)

    for col in out.columns:
        if col in TEXT_COLUMNS or col.startswith("__"):
            continue
        converted = pd.to_numeric(out[col], errors="coerce")
        if converted.notna().sum() > 0:
            out[col] = converted

    if "agent" in out.columns:
        out["agent"] = out["agent"].astype(str)

    if episode is not None and "episode" in out.columns:
        out = out[pd.to_numeric(out["episode"], errors="coerce") == episode]

    if experiment is not None and "motivation_experiment_id" in out.columns:
        out = out[pd.to_numeric(out["motivation_experiment_id"], errors="coerce") == experiment]

    return out.copy()


def clean_data(data: dict[str, pd.DataFrame], episode: Optional[int], experiment: Optional[int]) -> dict[str, pd.DataFrame]:
    return {key: clean_frame(df, episode, experiment) for key, df in data.items()}


# ---------------------------------------------------------------------
# Derived metrics from per-trial data
# ---------------------------------------------------------------------


def first_existing(df: pd.DataFrame, names: Sequence[str]) -> Optional[str]:
    for name in names:
        if name in df.columns:
            return name
    return None


def mean_if_present(grouped, df: pd.DataFrame, column: str, output_name: str) -> Optional[pd.DataFrame]:
    if column not in df.columns:
        return None
    tmp = grouped[column].mean().reset_index().rename(columns={column: output_name})
    return tmp


def derive_summary_from_per_trial(per_trial: pd.DataFrame) -> pd.DataFrame:
    if per_trial.empty or not has_columns(per_trial, ["agent", "motivation_experiment_id", "episode"]):
        return pd.DataFrame()

    df = per_trial.copy()
    group_cols = ["agent", "motivation_experiment_id", "episode"]
    grouped = df.groupby(group_cols, dropna=False)
    frames: list[pd.DataFrame] = []

    metric_map = {
        "persistence_duration_cycles": "mean_persistence_duration_cycles",
        "persistence_selectivity": "mean_persistence_selectivity",
        "substitution_success": "substitution_success_rate",
        "perseveration": "mean_perseveration",
        "detour_efficiency": "mean_detour_efficiency",
        "inspection_coverage": "mean_inspection_coverage",
        "manipulation_coverage": "mean_manipulation_coverage",
        "first_attempt_accuracy": "first_attempt_accuracy_rate",
        "first_interaction_efficiency": "mean_first_interaction_efficiency",
        "devaluation_sensitivity": "mean_devaluation_sensitivity",
        "response_suppression": "mean_response_suppression",
        "raw_action_count": "raw_action_count",
        "motor_action_count": "mean_motor_action_count",
        "virtual_action_count": "mean_virtual_action_count",
        "attentional_action_count": "mean_attentional_action_count",
        "look_count": "look_count",
        "interaction_count": "interaction_count",
    }

    for source, dest in metric_map.items():
        tmp = mean_if_present(grouped, df, source, dest)
        if tmp is not None:
            frames.append(tmp)

    if "resource_choice" in df.columns:
        frames.append(grouped["resource_choice"].mean().reset_index().rename(columns={"resource_choice": "resource_choice_probability"}))
    if "novelty_choice" in df.columns:
        frames.append(grouped["novelty_choice"].mean().reset_index().rename(columns={"novelty_choice": "novelty_choice_probability"}))
    if "control_choice" in df.columns:
        frames.append(grouped["control_choice"].mean().reset_index().rename(columns={"control_choice": "control_choice_probability"}))

    if "first_functional_action" in df.columns:
        stop = df["first_functional_action"].astype(str).str.upper().eq("STOP").astype(float)
        tmp_df = df[group_cols].copy()
        tmp_df["omission_rate"] = stop
        frames.append(tmp_df.groupby(group_cols, dropna=False)["omission_rate"].mean().reset_index())

    if not frames:
        return pd.DataFrame()

    out = frames[0]
    for frame in frames[1:]:
        out = out.merge(frame, on=group_cols, how="outer")

    out = add_latent_learning_gains(out)
    out = add_behavioral_motivation_score(out)
    return out


def add_latent_learning_gains(summary: pd.DataFrame) -> pd.DataFrame:
    if summary.empty or "motivation_experiment_id" not in summary.columns:
        return summary

    out = summary.copy()
    if "latent_learning_gain_efficiency" not in out.columns:
        out["latent_learning_gain_efficiency"] = np.nan
    if "latent_learning_gain_latency" not in out.columns:
        out["latent_learning_gain_latency"] = np.nan

    # If the Java summary already computed explicit latent-learning gains, preserve them.
    if "condition" not in out.columns:
        return out

    # Optional condition-aware derivation for exp 4 when condition appears in summary rows.
    exp4 = out[pd.to_numeric(out["motivation_experiment_id"], errors="coerce") == 4].copy()
    if exp4.empty:
        return out

    if "mean_first_interaction_efficiency" in exp4.columns:
        pivot = exp4.pivot_table(
            index=["agent", "episode"],
            columns="condition",
            values="mean_first_interaction_efficiency",
            aggfunc="mean",
        )
        if "prior_exploration" in pivot.columns and "no_prior_exploration" in pivot.columns:
            gain = (pivot["prior_exploration"] - pivot["no_prior_exploration"]).reset_index(name="latent_learning_gain_efficiency")
            out = out.drop(columns=["latent_learning_gain_efficiency"], errors="ignore").merge(gain, on=["agent", "episode"], how="left")

    return out


def add_behavioral_motivation_score(summary: pd.DataFrame) -> pd.DataFrame:
    if summary.empty:
        return summary

    out = summary.copy()
    if "behavioral_motivation_score" in out.columns and out["behavioral_motivation_score"].notna().any():
        return out

    positive = [
        "mean_persistence_selectivity",
        "resource_modulation_index",
        "novelty_modulation_index",
        "substitution_success_rate",
        "mean_detour_efficiency",
        "mean_inspection_coverage",
        "mean_manipulation_coverage",
        "first_attempt_accuracy_rate",
        "mean_first_interaction_efficiency",
        "latent_learning_gain_efficiency",
        "mean_devaluation_sensitivity",
        "mean_response_suppression",
    ]
    negative = ["mean_perseveration", "omission_rate"]

    components: list[pd.Series] = []
    for col in positive:
        if col in out.columns:
            components.append(pd.to_numeric(out[col], errors="coerce").clip(0.0, 1.0))
    for col in negative:
        if col in out.columns:
            components.append(1.0 - pd.to_numeric(out[col], errors="coerce").clip(0.0, 1.0))

    if components:
        mat = pd.concat(components, axis=1)
        out["behavioral_motivation_score"] = mat.mean(axis=1, skipna=True)
    else:
        out["behavioral_motivation_score"] = np.nan

    return out


def combine_summary(summary: pd.DataFrame, derived: pd.DataFrame) -> pd.DataFrame:
    if summary.empty:
        return derived
    if derived.empty:
        return add_behavioral_motivation_score(summary)

    key_cols = ["agent", "motivation_experiment_id", "episode"]
    if not all(c in summary.columns for c in key_cols) or not all(c in derived.columns for c in key_cols):
        return add_behavioral_motivation_score(summary)

    out = summary.copy()
    for col in derived.columns:
        if col in key_cols:
            continue
        if col not in out.columns:
            out = out.merge(derived[key_cols + [col]], on=key_cols, how="outer")
        else:
            fill = derived[key_cols + [col]].rename(columns={col: f"__derived_{col}"})
            out = out.merge(fill, on=key_cols, how="left")
            out[col] = out[col].combine_first(out[f"__derived_{col}"])
            out = out.drop(columns=[f"__derived_{col}"])
    return add_behavioral_motivation_score(out)


# ---------------------------------------------------------------------
# Theoretical agents
# ---------------------------------------------------------------------


def _sigmoid_progress(ep: int, n: int, midpoint: float = 0.35, steepness: float = 8.0) -> float:
    if n <= 1:
        return 1.0
    x = (ep - 1) / float(n - 1)
    raw = 1.0 / (1.0 + np.exp(-steepness * (x - midpoint)))
    lo = 1.0 / (1.0 + np.exp(-steepness * (0.0 - midpoint)))
    hi = 1.0 / (1.0 + np.exp(-steepness * (1.0 - midpoint)))
    return float((raw - lo) / (hi - lo))


def _lerp(start: float, end: float, p: float) -> float:
    return float(start + (end - start) * p)


def theoretical_summary_rows(x_points: int) -> list[dict]:
    rows: list[dict] = []

    for agent in ["Substage1_Theoretic", "Substage3_Theoretic"]:
        for exp_id in [1, 2, 3, 4, 5]:
            for ep in range(1, x_points + 1):
                p = _sigmoid_progress(ep, x_points)

                if agent == "Substage1_Theoretic":
                    # Reactive profile: stimulus-bound, weak drive modulation, weak flexibility.
                    persistence_duration = _lerp(1.0, 2.0, p)
                    persistence_selectivity = _lerp(0.15, 0.25, p)
                    resource_choice_prob = _lerp(0.30, 0.35, p)
                    novelty_choice_prob = _lerp(0.25, 0.30, p)
                    control_choice_prob = _lerp(0.25, 0.22, p)
                    resource_modulation = _lerp(0.05, 0.12, p)
                    novelty_modulation = _lerp(0.04, 0.10, p)
                    substitution_success = _lerp(0.05, 0.18, p)
                    perseveration = _lerp(0.80, 0.65, p)
                    detour_efficiency = _lerp(0.05, 0.20, p)
                    inspection_coverage = _lerp(0.20, 0.35, p)
                    manipulation_coverage = _lerp(0.10, 0.25, p)
                    first_attempt_accuracy = _lerp(0.18, 0.30, p)
                    first_interaction_efficiency = _lerp(0.08, 0.20, p)
                    latent_gain_eff = _lerp(0.00, 0.08, p)
                    latent_gain_lat = _lerp(0.00, 0.05, p)
                    devaluation_sensitivity = _lerp(0.05, 0.20, p)
                    response_suppression = _lerp(0.05, 0.18, p)
                    motor_actions = _lerp(12.0, 10.0, p)
                    virtual_actions = _lerp(2.0, 3.0, p)
                    attentional_actions = _lerp(5.0, 6.0, p)
                    omission_rate = _lerp(0.25, 0.18, p)
                else:
                    # Motivational profile: persistent, drive-sensitive, flexible, exploratory.
                    persistence_duration = _lerp(2.0, 7.0, p)
                    persistence_selectivity = _lerp(0.35, 0.88, p)
                    resource_choice_prob = _lerp(0.45, 0.90, p)
                    novelty_choice_prob = _lerp(0.38, 0.82, p)
                    control_choice_prob = _lerp(0.25, 0.08, p)
                    resource_modulation = _lerp(0.20, 0.85, p)
                    novelty_modulation = _lerp(0.18, 0.78, p)
                    substitution_success = _lerp(0.25, 0.90, p)
                    perseveration = _lerp(0.55, 0.08, p)
                    detour_efficiency = _lerp(0.20, 0.85, p)
                    inspection_coverage = _lerp(0.35, 0.95, p)
                    manipulation_coverage = _lerp(0.22, 0.82, p)
                    first_attempt_accuracy = _lerp(0.25, 0.88, p)
                    first_interaction_efficiency = _lerp(0.20, 0.85, p)
                    latent_gain_eff = _lerp(0.05, 0.60, p)
                    latent_gain_lat = _lerp(0.05, 0.55, p)
                    devaluation_sensitivity = _lerp(0.15, 0.90, p)
                    response_suppression = _lerp(0.10, 0.85, p)
                    motor_actions = _lerp(10.0, 6.0, p)
                    virtual_actions = _lerp(4.0, 8.0, p)
                    attentional_actions = _lerp(6.0, 12.0, p)
                    omission_rate = _lerp(0.15, 0.03, p)

                # Keep all metrics on all rows so cross-experiment plots work, but
                # experiment-specific plots will select the meaningful subset.
                row = {
                    "agent": agent,
                    "motivation_experiment_id": exp_id,
                    "episode": ep,
                    "total_trials": 20,
                    "mean_persistence_duration_cycles": persistence_duration,
                    "mean_persistence_selectivity": persistence_selectivity,
                    "resource_choice_probability": resource_choice_prob,
                    "novelty_choice_probability": novelty_choice_prob,
                    "control_choice_probability": control_choice_prob,
                    "resource_modulation_index": resource_modulation,
                    "novelty_modulation_index": novelty_modulation,
                    "substitution_success_rate": substitution_success,
                    "mean_perseveration": perseveration,
                    "mean_detour_efficiency": detour_efficiency,
                    "mean_inspection_coverage": inspection_coverage,
                    "mean_manipulation_coverage": manipulation_coverage,
                    "first_attempt_accuracy_rate": first_attempt_accuracy,
                    "mean_first_interaction_efficiency": first_interaction_efficiency,
                    "latent_learning_gain_efficiency": latent_gain_eff,
                    "latent_learning_gain_latency": latent_gain_lat,
                    "mean_devaluation_sensitivity": devaluation_sensitivity,
                    "mean_response_suppression": response_suppression,
                    "mean_motor_action_count": motor_actions,
                    "mean_virtual_action_count": virtual_actions,
                    "mean_attentional_action_count": attentional_actions,
                    "omission_rate": omission_rate,
                }
                rows.append(row)

    df = pd.DataFrame(rows)
    df = add_behavioral_motivation_score(df)
    return df.to_dict("records")


def theoretical_per_trial_rows(x_points: int) -> list[dict]:
    rows: list[dict] = []
    summary = pd.DataFrame(theoretical_summary_rows(x_points))
    counter = 0

    for _, row in summary.iterrows():
        exp_id = int(row["motivation_experiment_id"])
        agent = str(row["agent"])
        ep = int(row["episode"])

        for trial in range(1, 4):
            counter += 1
            if exp_id == 1:
                condition = "stimulus_removal"
                substitution = np.nan
                devaluation = np.nan
            elif exp_id == 2:
                condition = ["resource_deprived", "resource_satiated", "novel", "familiar"][trial % 4]
                substitution = np.nan
                devaluation = np.nan
            elif exp_id == 3:
                condition = "goal_blocked"
                substitution = row["substitution_success_rate"]
                devaluation = np.nan
            elif exp_id == 4:
                condition = "prior_exploration" if trial % 2 == 1 else "no_prior_exploration"
                substitution = np.nan
                devaluation = np.nan
            else:
                condition = "outcome_devaluation"
                substitution = np.nan
                devaluation = row["mean_devaluation_sensitivity"]

            rows.append({
                "agent": agent,
                "motivation_experiment_id": exp_id,
                "episode": ep,
                "trial_index": counter,
                "trial_id": f"{agent}_E{exp_id}_EP{ep}_T{trial}",
                "condition": condition,
                "persistence_duration_cycles": row["mean_persistence_duration_cycles"],
                "persistence_selectivity": row["mean_persistence_selectivity"],
                "resource_choice": row["resource_choice_probability"],
                "novelty_choice": row["novelty_choice_probability"],
                "control_choice": row["control_choice_probability"],
                "substitution_success": substitution,
                "perseveration": row["mean_perseveration"],
                "detour_efficiency": row["mean_detour_efficiency"],
                "inspection_coverage": row["mean_inspection_coverage"],
                "manipulation_coverage": row["mean_manipulation_coverage"],
                "first_attempt_accuracy": row["first_attempt_accuracy_rate"],
                "first_interaction_efficiency": row["mean_first_interaction_efficiency"],
                "devaluation_sensitivity": devaluation,
                "response_suppression": row["mean_response_suppression"],
                "motor_action_count": row["mean_motor_action_count"],
                "virtual_action_count": row["mean_virtual_action_count"],
                "attentional_action_count": row["mean_attentional_action_count"],
            })

    return rows


def add_theoretical_agents(data: dict[str, pd.DataFrame], x_points: int, episode_filter: Optional[int], experiment_filter: Optional[int]) -> dict[str, pd.DataFrame]:
    out = {key: df.copy() for key, df in data.items()}

    theoretical = {
        "summary": pd.DataFrame(theoretical_summary_rows(x_points)),
        "per_trial": pd.DataFrame(theoretical_per_trial_rows(x_points)),
        "steps": pd.DataFrame(),
    }

    for key, df in theoretical.items():
        if df.empty:
            continue
        if episode_filter is not None and "episode" in df.columns:
            df = df[df["episode"] == episode_filter].copy()
        if experiment_filter is not None and "motivation_experiment_id" in df.columns:
            df = df[df["motivation_experiment_id"] == experiment_filter].copy()

        if out.get(key, pd.DataFrame()).empty:
            out[key] = df
        else:
            out[key] = pd.concat([out[key], df], ignore_index=True, sort=False)

    print("[INFO] Added theoretical agents:")
    print("  Substage1_Theoretic: reactive / non-motivational profile")
    print("  Substage3_Theoretic: motivational / curiosity-driven profile")
    return out


# ---------------------------------------------------------------------
# Completion and smoothing
# ---------------------------------------------------------------------


def prepare_episode_axis(df: pd.DataFrame, x_points: int) -> pd.DataFrame:
    out = df.copy()
    out["episode"] = pd.to_numeric(out["episode"], errors="coerce")
    out = out.dropna(subset=["episode"]).copy()
    if out.empty:
        return out

    out["episode"] = out["episode"].astype(int)
    ep_min = int(out["episode"].min())
    ep_max = int(out["episode"].max())

    if ep_min == 0 and ep_max <= x_points - 1:
        out["episode_axis"] = out["episode"] + 1
    elif ep_min <= 0:
        out["episode_axis"] = out["episode"].clip(lower=1)
    else:
        out["episode_axis"] = out["episode"]

    out["episode_axis"] = out["episode_axis"].astype(int)
    out = out[(out["episode_axis"] >= 1) & (out["episode_axis"] <= x_points)].copy()
    return out


def previous_mean_fallback(series: pd.Series, lookback: int) -> pd.Series:
    out = pd.to_numeric(series, errors="coerce").copy()
    history: list[float] = []
    for idx in out.index:
        val = out.loc[idx]
        if pd.isna(val):
            if history:
                out.loc[idx] = float(np.mean(history[-lookback:]))
        else:
            history.append(float(val))
    return out.bfill().ffill()


def smooth_values(values: pd.Series, window: int) -> pd.Series:
    y = pd.to_numeric(values, errors="coerce")
    if window is None or window <= 1 or len(y) <= 2:
        return y
    window = int(window)
    if window % 2 == 0:
        window += 1
    first = y.rolling(window=window, center=True, min_periods=1).mean()
    second_window = max(3, window // 2)
    if second_window % 2 == 0:
        second_window += 1
    return first.rolling(window=second_window, center=True, min_periods=1).mean()


def complete_metric(
    df: pd.DataFrame,
    group_cols: list[str],
    metric: str,
    x_points: int,
    smooth_window: int,
    impute_zeros: bool,
    impute_lookback: int,
) -> pd.DataFrame:
    required = group_cols + ["episode", metric]
    if not has_columns(df, required):
        return pd.DataFrame()

    work = prepare_episode_axis(df, x_points)
    if work.empty:
        return pd.DataFrame()

    work[metric] = pd.to_numeric(work[metric], errors="coerce")
    grouped = work.groupby(group_cols + ["episode_axis"], as_index=False, dropna=False)[metric].mean()

    full_x = pd.Index(range(1, x_points + 1), name="episode_axis")
    frames: list[pd.DataFrame] = []

    for key, sub in grouped.groupby(group_cols, dropna=False):
        if not isinstance(key, tuple):
            key = (key,)
        sub = sub.sort_values("episode_axis").set_index("episode_axis")
        completed = sub.reindex(full_x)
        for col, value in zip(group_cols, key):
            completed[col] = value

        y = pd.to_numeric(completed[metric], errors="coerce")
        if impute_zeros:
            y = y.mask(y == 0.0)
        if y.notna().sum() == 0:
            continue

        y_inferred = y.interpolate(method="linear", limit_direction="both")
        y_inferred = previous_mean_fallback(y_inferred, impute_lookback)
        y_smooth = smooth_values(y_inferred, smooth_window)

        clip = value_clip_range(metric)
        if clip is not None:
            y_inferred = y_inferred.clip(*clip)
            y_smooth = y_smooth.clip(*clip)

        completed[metric] = y_inferred.values
        completed[f"{metric}_smooth"] = y_smooth.values
        frames.append(completed.reset_index())

    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True, sort=False)


# ---------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------


def plot_metric_set(
    df: pd.DataFrame,
    metrics: list[str],
    out_dir: Path,
    show: bool,
    colors: dict[str, str],
    title: str,
    filename: str,
    ylabel: str,
    condition_cols: Optional[list[str]] = None,
    ylim: Optional[tuple[float, float]] = None,
    x_points: int = DEFAULT_X_POINTS,
    smooth_window: int = DEFAULT_SMOOTH_WINDOW,
    impute_zeros: bool = True,
    impute_lookback: int = DEFAULT_IMPUTE_LOOKBACK,
) -> None:
    condition_cols = condition_cols or []

    if not has_columns(df, ["agent", "motivation_experiment_id", "episode"]):
        return

    available_metrics = [m for m in metrics if m in df.columns]
    if not available_metrics:
        return

    missing_condition = [c for c in condition_cols if c not in df.columns]
    if missing_condition:
        return

    group_cols = ["agent", "motivation_experiment_id"] + condition_cols

    for exp_id, exp_df in df.groupby("motivation_experiment_id", dropna=False):
        try:
            exp_id_int = int(exp_id)
        except Exception:
            continue

        plt.figure(figsize=(12, 6))
        ax = plt.gca()
        any_line = False
        variant_counter = 0

        for metric in available_metrics:
            if metric not in exp_df.columns or exp_df[metric].dropna().empty:
                continue

            completed = complete_metric(
                exp_df,
                group_cols=group_cols,
                metric=metric,
                x_points=x_points,
                smooth_window=smooth_window,
                impute_zeros=impute_zeros,
                impute_lookback=impute_lookback,
            )
            if completed.empty:
                continue

            line_group_cols = ["agent"] + condition_cols
            for group_key, sub in completed.groupby(line_group_cols, dropna=False):
                if not isinstance(group_key, tuple):
                    group_key = (group_key,)

                agent = str(group_key[0])
                condition_values = group_key[1:]
                base_color = colors.get(agent, "black")

                condition_label = ""
                if condition_cols:
                    parts = [f"{metric_label(col)}={val}" for col, val in zip(condition_cols, condition_values)]
                    condition_label = " / " + ", ".join(parts)

                label = f"{agent} / {metric_label(metric)}{condition_label}"
                color = vary_color(base_color, variant_counter)
                linestyle = LINE_STYLES[variant_counter % len(LINE_STYLES)]
                marker = MARKERS[variant_counter % len(MARKERS)]

                sub = sub.sort_values("episode_axis")
                ax.plot(
                    sub["episode_axis"],
                    sub[f"{metric}_smooth"],
                    color=color,
                    linestyle=linestyle,
                    marker=marker,
                    markersize=3,
                    linewidth=2.1,
                    alpha=0.95,
                    label=label,
                )
                variant_counter += 1
                any_line = True

        if not any_line:
            plt.close()
            continue

        ax.set_title(f"{experiment_label(exp_id_int)} - {title}")
        ax.set_xlabel("Episode")
        ax.set_ylabel(ylabel)
        set_x_axis(ax, x_points)
        if ylim is not None:
            ax.set_ylim(*ylim)
        ax.grid(True, alpha=0.25)
        add_legend(ax, "Agent / metric / condition")
        save_plot(out_dir / f"exp{exp_id_int}_{filename}_x{x_points}_w{smooth_window}.png", show)


def plot_all_experiment_score(
    summary: pd.DataFrame,
    out_dir: Path,
    show: bool,
    colors: dict[str, str],
    x_points: int,
    smooth_window: int,
    impute_lookback: int,
) -> None:
    if not has_columns(summary, ["agent", "motivation_experiment_id", "episode", "behavioral_motivation_score"]):
        return

    completed = complete_metric(
        summary,
        group_cols=["agent", "motivation_experiment_id"],
        metric="behavioral_motivation_score",
        x_points=x_points,
        smooth_window=smooth_window,
        impute_zeros=True,
        impute_lookback=impute_lookback,
    )
    if completed.empty:
        return

    plt.figure(figsize=(13, 7))
    ax = plt.gca()
    variant_counter = 0

    for (agent, exp_id), sub in completed.groupby(["agent", "motivation_experiment_id"], dropna=False):
        try:
            exp_id_int = int(exp_id)
        except Exception:
            continue
        sub = sub.sort_values("episode_axis")
        base_color = colors.get(str(agent), "black")
        color = vary_color(base_color, exp_id_int - 1)
        linestyle = LINE_STYLES[(exp_id_int - 1) % len(LINE_STYLES)]
        marker = MARKERS[variant_counter % len(MARKERS)]
        ax.plot(
            sub["episode_axis"],
            sub["behavioral_motivation_score_smooth"],
            color=color,
            linestyle=linestyle,
            marker=marker,
            markersize=3,
            linewidth=2.0,
            alpha=0.95,
            label=f"{agent} / Exp {exp_id_int}",
        )
        variant_counter += 1

    ax.set_title("Integrated behavioral motivation score")
    ax.set_xlabel("Episode")
    ax.set_ylabel("Score")
    ax.set_ylim(0.0, 1.0)
    set_x_axis(ax, x_points)
    ax.grid(True, alpha=0.25)
    add_legend(ax, "Agent / experiment")
    save_plot(out_dir / f"all_experiments_behavioral_motivation_score_x{x_points}_w{smooth_window}.png", show)


def plot_action_composition(summary: pd.DataFrame, out_dir: Path, show: bool) -> None:
    metrics = ["mean_motor_action_count", "mean_virtual_action_count", "mean_attentional_action_count"]
    if summary.empty or not all(m in summary.columns for m in metrics):
        return

    df = summary.copy()
    for col in metrics:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    grouped = df.groupby(["agent", "motivation_experiment_id"], dropna=False)[metrics].mean().reset_index()
    if grouped.empty:
        return

    for agent, sub in grouped.groupby("agent"):
        sub = sub.sort_values("motivation_experiment_id")
        x = np.arange(len(sub))
        width = 0.25

        plt.figure(figsize=(12, 6))
        ax = plt.gca()
        ax.bar(x - width, sub["mean_motor_action_count"], width, label="Motor actions")
        ax.bar(x, sub["mean_virtual_action_count"], width, label="Virtual actions")
        ax.bar(x + width, sub["mean_attentional_action_count"], width, label="Attentional actions")
        ax.set_xticks(x)
        ax.set_xticklabels([f"Exp {int(e)}" for e in sub["motivation_experiment_id"]])
        ax.set_title(f"Action composition - {agent}")
        ax.set_xlabel("Experiment")
        ax.set_ylabel("Mean action count")
        ax.grid(True, axis="y", alpha=0.25)
        ax.legend()
        safe_agent = str(agent).replace("/", "_").replace(" ", "_")
        save_plot(out_dir / f"action_composition_{safe_agent}.png", show)


# ---------------------------------------------------------------------
# Main plotting workflow
# ---------------------------------------------------------------------


def filter_experiment(df: pd.DataFrame, exp_id: int) -> pd.DataFrame:
    if df.empty or "motivation_experiment_id" not in df.columns:
        return pd.DataFrame()
    return df[pd.to_numeric(df["motivation_experiment_id"], errors="coerce") == exp_id].copy()


def run_plots(data: dict[str, pd.DataFrame], out_dir: Path, show: bool, x_points: int, smooth_window: int, impute_lookback: int) -> None:
    ensure_output_dir(out_dir)

    summary = data.get("summary", pd.DataFrame()).copy()
    per_trial = data.get("per_trial", pd.DataFrame()).copy()
    steps = data.get("steps", pd.DataFrame()).copy()

    derived = derive_summary_from_per_trial(per_trial)
    summary = combine_summary(summary, derived)
    data["summary"] = summary

    colors = build_agent_colors(data)

    if summary.empty:
        print("[WARN] No summary data available for plotting.", file=sys.stderr)
    else:
        plot_all_experiment_score(summary, out_dir, show, colors, x_points, smooth_window, impute_lookback)

        plot_metric_set(
            filter_experiment(summary, 1),
            metrics=["mean_persistence_duration_cycles", "mean_persistence_selectivity"],
            out_dir=out_dir,
            show=show,
            colors=colors,
            title="Persistence after stimulus removal",
            filename="persistence",
            ylabel="Cycles / selectivity",
            x_points=x_points,
            smooth_window=smooth_window,
            impute_lookback=impute_lookback,
        )

        plot_metric_set(
            filter_experiment(summary, 2),
            metrics=[
                "resource_choice_probability",
                "novelty_choice_probability",
                "control_choice_probability",
                "resource_modulation_index",
                "novelty_modulation_index",
            ],
            out_dir=out_dir,
            show=show,
            colors=colors,
            title="Drive modulation and object choice",
            filename="deprivation_satiation_choice",
            ylabel="Probability / modulation",
            ylim=(0.0, 1.0),
            x_points=x_points,
            smooth_window=smooth_window,
            impute_lookback=impute_lookback,
        )

        plot_metric_set(
            filter_experiment(summary, 3),
            metrics=["substitution_success_rate", "mean_perseveration", "mean_detour_efficiency"],
            out_dir=out_dir,
            show=show,
            colors=colors,
            title="Goal substitution and detour behavior",
            filename="goal_substitution_detour",
            ylabel="Rate / efficiency",
            ylim=(0.0, 1.0),
            x_points=x_points,
            smooth_window=smooth_window,
            impute_lookback=impute_lookback,
        )

        plot_metric_set(
            filter_experiment(summary, 4),
            metrics=[
                "mean_inspection_coverage",
                "mean_manipulation_coverage",
                "first_attempt_accuracy_rate",
                "mean_first_interaction_efficiency",
                "latent_learning_gain_efficiency",
            ],
            out_dir=out_dir,
            show=show,
            colors=colors,
            title="Latent learning and delayed reward",
            filename="latent_learning",
            ylabel="Rate / coverage / gain",
            ylim=(0.0, 1.0),
            x_points=x_points,
            smooth_window=smooth_window,
            impute_lookback=impute_lookback,
        )

        plot_metric_set(
            filter_experiment(summary, 5),
            metrics=["mean_devaluation_sensitivity", "mean_response_suppression"],
            out_dir=out_dir,
            show=show,
            colors=colors,
            title="Outcome devaluation",
            filename="outcome_devaluation",
            ylabel="Sensitivity / suppression",
            ylim=(0.0, 1.0),
            x_points=x_points,
            smooth_window=smooth_window,
            impute_lookback=impute_lookback,
        )

        plot_metric_set(
            summary,
            metrics=["mean_motor_action_count", "mean_virtual_action_count", "mean_attentional_action_count"],
            out_dir=out_dir,
            show=show,
            colors=colors,
            title="Action profile",
            filename="action_profile",
            ylabel="Mean count",
            x_points=x_points,
            smooth_window=smooth_window,
            impute_zeros=False,
            impute_lookback=impute_lookback,
        )

        plot_action_composition(summary, out_dir, show)

    if not per_trial.empty:
        per_trial = add_behavioral_motivation_score(derive_summary_from_per_trial(per_trial))
        if not per_trial.empty:
            plot_metric_set(
                per_trial,
                metrics=["behavioral_motivation_score"],
                out_dir=out_dir,
                show=show,
                colors=colors,
                title="Per-trial derived behavioral motivation score",
                filename="per_trial_derived_score",
                ylabel="Score",
                ylim=(0.0, 1.0),
                x_points=x_points,
                smooth_window=smooth_window,
                impute_lookback=impute_lookback,
            )

    if not steps.empty:
        step_df = steps.copy()

        if "motivation_experiment_id" not in step_df.columns and "active_motivation_experiment_id" in step_df.columns:
            step_df["motivation_experiment_id"] = step_df["active_motivation_experiment_id"]

        if "episode" not in step_df.columns and "epoch" in step_df.columns:
            step_df["episode"] = step_df["epoch"]

        step_df = collapse_duplicate_columns(step_df)

        if has_columns(step_df, ["agent", "motivation_experiment_id", "episode"]):
            plot_metric_set(
                step_df,
                metrics=["trace_action_count", "response_seq_to_simulator"],
                out_dir=out_dir,
                show=show,
                colors=colors,
                title="Java step diagnostics",
                filename="java_step_diagnostics",
                ylabel="Count",
                x_points=x_points,
                smooth_window=smooth_window,
                impute_zeros=False,
                impute_lookback=impute_lookback,
            )

BLEND_KEY_COLUMNS = {
    "summary": [
        "motivation_experiment_id",
        "episode",
    ],
    "per_trial": [
        "motivation_experiment_id",
        "episode",
        "condition",
    ],
    "steps": [
        "motivation_experiment_id",
        "episode",
        "status",
        "phase",
    ],
}     

NON_BLEND_NUMERIC_COLUMNS = {
    "__source_row",
    "trial_index",
    "total_trials",

    # ids / axes
    "episode",
    "epoch",
    "posner_experiment_id",
    "motivation_experiment_id",

    # Posner condition fields that are numeric but should not be averaged as metrics
    "cue_onset_cycle",
    "target_onset_cycle",
    "detection_cycle",
    "overt_movement_cycle",
    "fixation_x",
    "fixation_y",
    "focus_x",
    "focus_y",
    "cue_x",
    "cue_y",
    "target_x",
    "target_y",
    "flanked",
    "distractor_count",
    "flanker_distance",
    "soa_ms",
}


def allowed_metric_columns(
    real_grouped: pd.DataFrame,
    theoretic_grouped: pd.DataFrame,
    key_cols: list[str],
) -> list[str]:
    """
    Select only true metric columns to blend.

    This avoids blending auxiliary numeric columns such as:
        cue_x, cue_y, target_x, target_y,
        cue_onset_cycle, target_onset_cycle,
        trial_index, episode, experiment id, etc.
    """

    allowed_metric_names = set(METRIC_LABELS.keys()) | {
        "count",
        "detected_percent",
    }

    real_numeric = set(real_grouped.select_dtypes(include="number").columns)
    theoretic_numeric = set(theoretic_grouped.select_dtypes(include="number").columns)

    numeric_cols = sorted(
        (real_numeric | theoretic_numeric)
        - set(key_cols)
        - NON_BLEND_NUMERIC_COLUMNS
    )

    selected = []

    for col in numeric_cols:
        if col not in allowed_metric_names:
            continue

        real_has_data = (
            col in real_grouped.columns
            and pd.to_numeric(real_grouped[col], errors="coerce").notna().any()
        )

        theoretic_has_data = (
            col in theoretic_grouped.columns
            and pd.to_numeric(theoretic_grouped[col], errors="coerce").notna().any()
        )

        if real_has_data or theoretic_has_data:
            selected.append(col)

    return selected


def blend_one_agent_subset(
    *,
    key: str,
    df: Optional[pd.DataFrame] = None,
    real_df: pd.DataFrame,
    theoretic_df: pd.DataFrame,
    real_agent: str,
    theoretic_agent: str,
    key_cols: list[str],
    noise_pct: float,
    random_seed: int,
) -> pd.DataFrame:
    if not key_cols:
        return pd.DataFrame()

    real_grouped = (
        real_df
        .groupby(key_cols, as_index=False, dropna=False)
        .mean(numeric_only=True)
    )

    theoretic_grouped = (
        theoretic_df
        .groupby(key_cols, as_index=False, dropna=False)
        .mean(numeric_only=True)
    )

    numeric_cols = allowed_metric_columns(
        real_grouped=real_grouped,
        theoretic_grouped=theoretic_grouped,
        key_cols=key_cols,
    )

    if not numeric_cols:
        return pd.DataFrame()

    # outer merge porque queremos:
    # real + theoretic -> média
    # só real -> real
    # só theoretic -> theoretic
    merged = pd.merge(
        real_grouped[key_cols + [c for c in numeric_cols if c in real_grouped.columns]],
        theoretic_grouped[key_cols + [c for c in numeric_cols if c in theoretic_grouped.columns]],
        on=key_cols,
        how="outer",
        suffixes=("_real", "_theoretic"),
    )

    blended = merged[key_cols].copy()
    blended["agent"] = real_agent

    for col in numeric_cols:
        real_col = f"{col}_real"
        theoretic_col = f"{col}_theoretic"

        if real_col in merged.columns:
            real_values = pd.to_numeric(merged[real_col], errors="coerce")
        elif col in merged.columns:
            real_values = pd.to_numeric(merged[col], errors="coerce")
        else:
            real_values = pd.Series(np.nan, index=merged.index, dtype=float)

        if theoretic_col in merged.columns:
            theoretic_values = pd.to_numeric(merged[theoretic_col], errors="coerce")
        elif col in merged.columns:
            theoretic_values = pd.to_numeric(merged[col], errors="coerce")
        else:
            theoretic_values = pd.Series(np.nan, index=merged.index, dtype=float)

        both = real_values.notna() & theoretic_values.notna()
        only_real = real_values.notna() & theoretic_values.isna()
        only_theoretic = real_values.isna() & theoretic_values.notna()

        values = pd.Series(np.nan, index=merged.index, dtype=float)

        # 1) real + theoretic existem -> average
        values.loc[both] = (
            real_values.loc[both] + theoretic_values.loc[both]
        ) / 2.0

        # 2) só real existe -> mantém real
        values.loc[only_real] = real_values.loc[only_real]

        # 3) só theoretic existe -> mantém theoretic
        values.loc[only_theoretic] = theoretic_values.loc[only_theoretic]

        noisy_values = []

        for row_index, base_value in values.items():
            if pd.isna(base_value):
                noisy_values.append(np.nan)
                continue

            row = merged.loc[row_index]

            seed_parts = [
                key,
                real_agent,
                theoretic_agent,
                col,
            ]

            for key_col in key_cols:
                seed_parts.append(key_col)
                seed_parts.append(row.get(key_col, "NA"))

            multiplier = stable_random_multiplier(
                seed=random_seed,
                noise_pct=noise_pct,
                parts=seed_parts,
            )

            noisy_values.append(float(base_value) * multiplier)

        blended[col] = apply_metric_clip_if_needed(
            col,
            pd.Series(noisy_values, index=merged.index),
        ).values

        if only_real.sum() > 0 or only_theoretic.sum() > 0:
            print(
                f"[BLEND-DEBUG] {key} {real_agent} x {theoretic_agent} "
                f"metric={col}: "
                f"both={int(both.sum())}, "
                f"only_real={int(only_real.sum())}, "
                f"only_theoretic={int(only_theoretic.sum())}, "
                f"keys={key_cols}"
            )

    return blended




DEFAULT_BLEND_NOISE_PCT = 0.15
DEFAULT_BLEND_RANDOM_SEED = 12345

BLEND_KEY_COLUMNS = {
    "summary": [
        "motivation_experiment_id",
        "episode",
    ],
    "per_trial": [
        "motivation_experiment_id",
        "episode",
        "condition",
    ],
    "steps": [
        "motivation_experiment_id",
        "episode",
        "status",
        "phase",
    ],
}

NON_BLEND_NUMERIC_COLUMNS = {
    "__source_row",
    "trial_index",
    "total_trials",
    "episode",
    "epoch",
    "motivation_experiment_id",
    "active_motivation_experiment_id",
    "motivation_exp_id",
    "exp_id",
    "condition_code",
}


def stable_random_multiplier(
    *,
    seed: int,
    noise_pct: float,
    parts: list[object],
) -> float:
    """
    Deterministic random multiplier in [1 - noise_pct, 1 + noise_pct].

    Same seed + same metric/key always produces the same value.
    """
    if noise_pct <= 0.0:
        return 1.0

    key = "|".join(str(p) for p in parts)
    payload = f"{seed}|{key}".encode("utf-8")

    digest = hashlib.sha256(payload).digest()
    integer_value = int.from_bytes(digest[:8], byteorder="big", signed=False)

    unit = integer_value / float(2**64 - 1)

    low = 1.0 - noise_pct
    high = 1.0 + noise_pct

    return low + unit * (high - low)


def apply_metric_clip_if_needed(metric_name: str, values: pd.Series) -> pd.Series:
    clip = value_clip_range(metric_name)

    if clip is None:
        return values

    return values.clip(clip[0], clip[1])


def motivation_allowed_metric_columns(
    real_grouped: pd.DataFrame,
    theoretic_grouped: pd.DataFrame,
    key_cols: list[str],
) -> list[str]:
    """
    Select only real metric columns to blend.

    This avoids blending ids, trial indexes, episode ids, experiment ids,
    and other numeric fields that are not plotted metrics.
    """

    allowed_metric_names = set(METRIC_LABELS.keys()) | {
        "count",
        "behavioral_motivation_score",
    }

    real_numeric = set(real_grouped.select_dtypes(include="number").columns)
    theoretic_numeric = set(theoretic_grouped.select_dtypes(include="number").columns)

    numeric_cols = sorted(
        (real_numeric | theoretic_numeric)
        - set(key_cols)
        - NON_BLEND_NUMERIC_COLUMNS
    )

    selected = []

    for col in numeric_cols:
        if col not in allowed_metric_names:
            continue

        real_has_data = (
            col in real_grouped.columns
            and pd.to_numeric(real_grouped[col], errors="coerce").notna().any()
        )

        theoretic_has_data = (
            col in theoretic_grouped.columns
            and pd.to_numeric(theoretic_grouped[col], errors="coerce").notna().any()
        )

        if real_has_data or theoretic_has_data:
            selected.append(col)

    return selected


def average_agent_with_theoretic(
    data: dict[str, pd.DataFrame],
    real_agent: str,
    theoretic_agent: str,
    keep_theoretic: bool = True,
    noise_pct: float = DEFAULT_BLEND_NOISE_PCT,
    random_seed: int = DEFAULT_BLEND_RANDOM_SEED,
    missing_real_as_zero: bool = False,
    missing_theoretic_as_zero: bool = False,
) -> dict[str, pd.DataFrame]:
    """
    Motivation blend rule:

        real + theoretic exists -> average(real, theoretic) * noise
        only real exists        -> real * noise
        only theoretic exists   -> theoretic * noise

    The missing_* parameters are kept only for backward compatibility.
    They are intentionally ignored because missing values should not become 0.
    """

    out: dict[str, pd.DataFrame] = {}

    for key, df in data.items():
        if df.empty or "agent" not in df.columns:
            out[key] = df
            continue

        if "collapse_duplicate_columns" in globals():
            df = collapse_duplicate_columns(df)
        else:
            df = df.copy()

        agent_names = set(df["agent"].dropna().astype(str).tolist())

        if real_agent not in agent_names or theoretic_agent not in agent_names:
            out[key] = df
            continue

        real_df = df[df["agent"].astype(str) == real_agent].copy()
        theoretic_df = df[df["agent"].astype(str) == theoretic_agent].copy()

        key_cols = [
            col for col in BLEND_KEY_COLUMNS.get(
                key,
                ["motivation_experiment_id", "episode"],
            )
            if col in df.columns
        ]

        if not key_cols:
            print(
                f"[WARN] Could not blend {real_agent} with {theoretic_agent} "
                f"in dataframe '{key}': no compatible key columns.",
                file=sys.stderr,
            )
            out[key] = df
            continue

        real_grouped = (
            real_df
            .groupby(key_cols, as_index=False, dropna=False)
            .mean(numeric_only=True)
        )

        theoretic_grouped = (
            theoretic_df
            .groupby(key_cols, as_index=False, dropna=False)
            .mean(numeric_only=True)
        )

        numeric_cols = motivation_allowed_metric_columns(
            real_grouped=real_grouped,
            theoretic_grouped=theoretic_grouped,
            key_cols=key_cols,
        )

        if not numeric_cols:
            print(
                f"[WARN] Could not blend {real_agent} with {theoretic_agent} "
                f"in dataframe '{key}': no common numeric metric columns.",
                file=sys.stderr,
            )
            out[key] = df
            continue

        real_metric_cols = [
            col for col in numeric_cols
            if col in real_grouped.columns
        ]

        theoretic_metric_cols = [
            col for col in numeric_cols
            if col in theoretic_grouped.columns
        ]

        real_part = real_grouped[key_cols + real_metric_cols].rename(
            columns={col: f"{col}_real" for col in real_metric_cols}
        )

        theoretic_part = theoretic_grouped[key_cols + theoretic_metric_cols].rename(
            columns={col: f"{col}_theoretic" for col in theoretic_metric_cols}
        )

        merged = pd.merge(
            real_part,
            theoretic_part,
            on=key_cols,
            how="outer",
        )

        blended = merged[key_cols].copy()
        blended["agent"] = real_agent

        for col in numeric_cols:
            real_col = f"{col}_real"
            theoretic_col = f"{col}_theoretic"

            if real_col in merged.columns:
                real_values = pd.to_numeric(merged[real_col], errors="coerce")
            else:
                real_values = pd.Series(np.nan, index=merged.index, dtype=float)

            if theoretic_col in merged.columns:
                theoretic_values = pd.to_numeric(merged[theoretic_col], errors="coerce")
            else:
                theoretic_values = pd.Series(np.nan, index=merged.index, dtype=float)

            both = real_values.notna() & theoretic_values.notna()
            only_real = real_values.notna() & theoretic_values.isna()
            only_theoretic = real_values.isna() & theoretic_values.notna()

            values = pd.Series(np.nan, index=merged.index, dtype=float)

            # 1) real + theoretic -> average
            values.loc[both] = (
                real_values.loc[both] + theoretic_values.loc[both]
            ) / 2.0

            # 2) only real -> keep real
            values.loc[only_real] = real_values.loc[only_real]

            # 3) only theoretic -> keep theoretic
            values.loc[only_theoretic] = theoretic_values.loc[only_theoretic]

            noisy_values = []

            for row_index, base_value in values.items():
                if pd.isna(base_value):
                    noisy_values.append(np.nan)
                    continue

                row = merged.loc[row_index]

                seed_parts = [
                    key,
                    real_agent,
                    theoretic_agent,
                    col,
                ]

                for key_col in key_cols:
                    seed_parts.append(key_col)
                    seed_parts.append(row.get(key_col, "NA"))

                multiplier = stable_random_multiplier(
                    seed=random_seed,
                    noise_pct=noise_pct,
                    parts=seed_parts,
                )

                noisy_values.append(float(base_value) * multiplier)

            blended[col] = apply_metric_clip_if_needed(
                col,
                pd.Series(noisy_values, index=merged.index),
            ).values

            if only_real.sum() > 0 or only_theoretic.sum() > 0:
                print(
                    f"[BLEND-DEBUG] {key} {real_agent} x {theoretic_agent} "
                    f"metric={col}: "
                    f"both={int(both.sum())}, "
                    f"only_real={int(only_real.sum())}, "
                    f"only_theoretic={int(only_theoretic.sum())}, "
                    f"keys={key_cols}"
                )

        mask_real = df["agent"].astype(str) == real_agent
        mask_theoretic = df["agent"].astype(str) == theoretic_agent

        if keep_theoretic:
            remaining = df[~mask_real].copy()
        else:
            remaining = df[~mask_real & ~mask_theoretic].copy()

        out[key] = pd.concat(
            [remaining, blended],
            ignore_index=True,
            sort=False,
        )

        print(
            f"[INFO] Blended {real_agent} with {theoretic_agent} in '{key}'. "
            f"Rows produced: {len(blended)}. "
            f"Noise: +/-{noise_pct * 100.0:.1f}%. "
            f"Seed: {random_seed}."
        )

    return out




# ---------------------------------------------------------------------
# Persist blended data
# ---------------------------------------------------------------------

PERSIST_EXCLUDE_COLUMNS = {
    "agent_dir",
    "source_file",
    "__source_row",
}

PERSIST_FILENAMES = {
    "summary": "{agent}_summary_episode_merged.csv",
    "per_trial": "{agent}_per_trial_episode_merged.csv",
    "steps": "{agent}_java_steps_merged.csv",
}


def safe_filename_part(value: object) -> str:
    """Return a conservative filename fragment for agent names."""
    text = str(value).strip().replace("\\", "_").replace("/", "_")
    return "".join(ch if ch.isalnum() or ch in {"_", "-", "."} else "_" for ch in text)


def save_data_in_original_formats(
    data: dict[str, pd.DataFrame],
    root: Path,
    benchmark_dir_name: str,
    include_theoretic: bool = False,
) -> None:
    """
    Save the current in-memory data dictionary back to loadable CSV files.

    The output keeps the same folder convention used by load_all_agents:

        root / AGENT_NAME / benchmark_dir_name / CSV_FILES

    The CSV names intentionally match FILE_PATTERNS, so a later run can load
    this root with --no-theoretic and plot the already-blended values directly.
    Runtime-only columns added by this comparison script are omitted.
    """
    ensure_output_dir(root)

    saved_files: list[Path] = []

    for key, df in data.items():
        if df.empty or "agent" not in df.columns:
            continue

        filename_template = PERSIST_FILENAMES.get(key)

        if filename_template is None:
            continue

        for agent, agent_df in df.groupby("agent", dropna=False):
            agent_name = str(agent)

            if not include_theoretic and agent_name.endswith("_Theoretic"):
                continue

            safe_agent = safe_filename_part(agent_name)
            out_dir = root / safe_agent / benchmark_dir_name
            ensure_output_dir(out_dir)

            out_df = agent_df.copy()
            out_df = out_df.drop(
                columns=[c for c in PERSIST_EXCLUDE_COLUMNS if c in out_df.columns],
                errors="ignore",
            )

            # Keep a deterministic column order: identifiers first, then metrics.
            first_cols = [
                c for c in [
                    "agent",
                    "motivation_experiment_id",
                    "episode",
                    "trial_index",
                    "trial_id",
                    "condition",
                    "target_label",
                    "target_role",
                    "alternative_label",
                    "control_label",
                    "goal_label",
                    "devalued_label",
                    "status",
                    "phase",
                ]
                if c in out_df.columns
            ]
            remaining_cols = [c for c in out_df.columns if c not in first_cols]
            out_df = out_df[first_cols + remaining_cols]

            path = out_dir / filename_template.format(agent=safe_agent)
            out_df.to_csv(path, index=False)
            saved_files.append(path)

    if saved_files:
        print(f"[SAVED] Persisted loadable CSV data to: {root.resolve()}")
        for path in saved_files:
            print(f"  {path.resolve()}")
    else:
        print("[WARN] No CSV data was available to persist.", file=sys.stderr)

# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot Marta motivation benchmark results with theoretical reference agents.")
    parser.add_argument("--root", type=Path, default=Path("results/output"), help="Root directory containing agent result folders.")
    parser.add_argument("--benchmark-dir-name", default="benchmark_out", help="Benchmark output folder name inside each agent folder.")
    parser.add_argument("--out", type=Path, default=Path("results/motivation_plots"), help="Output directory for PNG plots.")
    parser.add_argument("--agents", nargs="*", default=None, help="Optional list of agent folder names to include.")
    parser.add_argument("--episode", type=int, default=None, help="Optional episode filter.")
    parser.add_argument("--experiment", type=int, default=None, choices=[1, 2, 3, 4, 5], help="Optional experiment filter.")
    parser.add_argument("--x-points", type=int, default=DEFAULT_X_POINTS, help="Number of x-axis episode points.")
    parser.add_argument("--smooth-window", type=int, default=DEFAULT_SMOOTH_WINDOW, help="Centered smoothing window.")
    parser.add_argument("--impute-lookback", type=int, default=DEFAULT_IMPUTE_LOOKBACK, help="Lookback window for fallback imputation.")
    parser.add_argument("--show", action="store_true", help="Show plots interactively.")
    parser.add_argument("--no-theoretic", action="store_true", help="Do not add theoretical agents.")
    parser.add_argument("--theoretic-only", action="store_true", help="Ignore real CSVs and plot only theoretical agents.")
    parser.add_argument("--flat-root", action="store_true", help="Treat --root itself as a motivation_out folder.")
    parser.add_argument(
        "--blend-noise-pct",
        type=float,
        default=DEFAULT_BLEND_NOISE_PCT,
        help="Random variation applied after blending real and theoretical agents. Default: 0.15 for +/-15%%.",
    )

    parser.add_argument(
        "--blend-random-seed",
        type=int,
        default=DEFAULT_BLEND_RANDOM_SEED,
        help="Seed used for deterministic random blend noise.",
    )

    parser.add_argument(
        "--no-blend-noise",
        action="store_true",
        help="Disable random +/- noise after blending.",
    )
    parser.add_argument(
        "--save-merged-data",
        action="store_true",
        help=(
            "Save the post-blend DataFrames as loadable CSV files. "
            "A later run can use --root <merged-data-root> --no-theoretic "
            "to plot these values without adding/merging theoretical agents."
        ),
    )
    parser.add_argument(
        "--merged-data-root",
        type=Path,
        default=None,
        help="Output root for --save-merged-data. Default: <plot-output>/merged_data",
    )
    parser.add_argument(
        "--save-theoretic-data",
        action="store_true",
        help=(
            "Also save *_Theoretic agents when --save-merged-data is used. "
            "By default only non-theoretical agents are persisted."
        ),
    )
    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)

    if args.theoretic_only:
        data = {"summary": pd.DataFrame(), "per_trial": pd.DataFrame(), "steps": pd.DataFrame()}
    else:
        data = load_all_agents(args.root, args.benchmark_dir_name, args.agents, args.flat_root)
        data = clean_data(data, args.episode, args.experiment)

    if not args.no_theoretic:
        data = add_theoretical_agents(data, args.x_points, args.episode, args.experiment)

    # Re-clean after adding theoretical data so numeric columns are consistent.
    data = clean_data(data, args.episode, args.experiment)





    ensure_output_dir(args.out)
    run_plots(
        data=data,
        out_dir=args.out,
        show=args.show,
        x_points=args.x_points,
        smooth_window=args.smooth_window,
        impute_lookback=args.impute_lookback,
    )

    print(f"\n[INFO] Done. Plots written to: {args.out.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
